### ISSUE TITLE
Some issues related to its footstep plannner

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-Common#22]
I got some issues of Thormang3 footstep planner in gazebo.

1. Its footstep planner can not return footsteps when x is greater than 2.0
2. direct walking works fine, but thormang3 falls down when footsteps are executed.

**Comment by kaym9n** [comment]
1. The footstep planner uses the map to avoid obstacles. The default version uses a empty map. The size of the empty map is 4m x 4m. That's why the planner did not return the footprint.  
   - [navigation launch file ](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-OPC/blob/master/thormang3_navigation/launch/thormang3_footstep_planner.launch)
   - maps : [empty.gif](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-OPC/blob/master/thormang3_navigation/maps/empty.gif), [empty.yaml](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-OPC/blob/master/thormang3_navigation/maps/empty.yaml)  

2. We did not fine-tune the gazebo environment.
